<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Cmas_360_Agent" duration-ms="80537" started-at="2020-10-30T07:44:00Z" finished-at="2020-10-30T07:45:20Z">
    <groups>
    </groups>
    <test name="save_testcases" duration-ms="46422" started-at="2020-10-30T07:44:00Z" finished-at="2020-10-30T07:44:46Z">
      <class name="testCases.TC_001">
        <test-method status="PASS" signature="login()[pri:0, instance:testCases.TC_001@59f99ea]" name="login" duration-ms="46378" started-at="2020-10-30T07:44:00Z" finished-at="2020-10-30T07:44:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_001@59f99ea]" name="teardown" is-config="true" duration-ms="23" started-at="2020-10-30T07:44:46Z" finished-at="2020-10-30T07:44:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=TC_001.login()[pri:0, instance:testCases.TC_001@59f99ea] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_001 -->
    </test> <!-- save_testcases -->
    <test name="Check_testcases" duration-ms="21335" started-at="2020-10-30T07:44:46Z" finished-at="2020-10-30T07:45:08Z">
      <class name="testCases.TC_002">
        <test-method status="FAIL" signature="failedtest()[pri:0, instance:testCases.TC_002@13deb50e]" name="failedtest" duration-ms="20009" started-at="2020-10-30T07:44:46Z" finished-at="2020-10-30T07:45:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [aran] but found [waran]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [aran] but found [waran]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC_002.failedtest(TC_002.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtest -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_002@13deb50e]" name="teardown" is-config="true" duration-ms="1325" started-at="2020-10-30T07:45:06Z" finished-at="2020-10-30T07:45:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failedtest status=FAILURE method=TC_002.failedtest()[pri:0, instance:testCases.TC_002@13deb50e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC_002 -->
    </test> <!-- Check_testcases -->
    <test name="cancel_testcases" duration-ms="12738" started-at="2020-10-30T07:45:08Z" finished-at="2020-10-30T07:45:20Z">
      <class name="testCases.TC_003">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TC_003@5f341870]" name="launchBrowser" is-config="true" duration-ms="9491" started-at="2020-10-30T07:43:50Z" finished-at="2020-10-30T07:44:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="failedtest()[pri:0, instance:testCases.TC_003@5f341870]" name="failedtest" duration-ms="12736" started-at="2020-10-30T07:45:08Z" finished-at="2020-10-30T07:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedtest -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testCases.TC_003@5f341870]" name="teardown" is-config="true" duration-ms="0" started-at="2020-10-30T07:45:20Z" finished-at="2020-10-30T07:45:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failedtest status=SUCCESS method=TC_003.failedtest()[pri:0, instance:testCases.TC_003@5f341870] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="close()[pri:0, instance:testCases.TC_003@5f341870]" name="close" is-config="true" duration-ms="195" started-at="2020-10-30T07:45:20Z" finished-at="2020-10-30T07:45:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- testCases.TC_003 -->
    </test> <!-- cancel_testcases -->
  </suite> <!-- Cmas_360_Agent -->
</testng-results>
